---
title       : Play Data, Play Ball! (II)
subtitle    : Dig Deeper
author      : Summit Suen
job         : Taiwan R User Group
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Recap

- [BUx edX | Sabermetrics 101: Introduction to Baseball Analytics](https://www.edx.org/course/sabermetrics-101-introduction-baseball-bux-sabr101x-0)

- [Lahman Database](http://lahman.r-forge.r-project.org/)
- [pitchRx](http://cpsievert.github.io/pitchRx/#2D_animation)
- [openWAR](https://baseballwithr.wordpress.com/2014/03/17/introduction-to-openwar/)

- [RSelenium](http://ropensci.github.io/RSelenium/)
- [phantomJS](http://phantomjs.org/)

---

## Sabermetrics: 

- Pythagorean theorem

$$latex
f(x;\mu,\sigma^2) = \frac{1}{\sigma\sqrt{2\pi}} 
e^{ -\frac{1}{2}\left(\frac{x-\mu}{\sigma}\right)^2 }
$$

- Runs Created formula

- Win Above Replacement

---

## openWAR

```{r}
require(openWAR)
source("~/Documents/openWAR/R/GameDay.R")
getGameIds(date=as.Date("2015-04-05"))
gd = gameday(gameId="gid_2015_04_05_slnmlb_chnmlb_1")
```

---

## openWAR

```{r}
summary(gd$ds)
```

---

## Data Source

- lahman database
- MLBAM: Gameday

---

## openWAR

```{r}

```

## CPBL

---

## Early Power Surge: is that real?

